### ISSUE TITLE
Issues with some of the pages loading at all.

### ISSUE THREAD

**Issue by MJpoland** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#1]
I've noticed that after installing your script about a half of pages on youtube videos not load at all
![error](https://user-images.githubusercontent.com/9215148/106611593-73477880-6568-11eb-9e6f-06255aa1c52b.png)

**Comment by zerodytrash** [comment]
I assume that this is the reason:
#b5727997ee6d9f9b3b95da4691fb9fcc1530b9f6

if not, i need more info:
- which browser?
- which extension are activated?

**Comment by Marfjeh** [comment]
Im having the same problem.

I'm using Firefox 86.0 (64-bit)
Extensions: Ublock origin. Bitwqarden. Tampermonkey (only this user script enabled)

I noticed that ublock origin was blocking content as the numbers keep going up during page load. after disabling ublock origin, the page did load. but now with a js error:
```
Simple-YouTube-Age-Restriction-Bypass-Error: Simple-YouTube-Age-Restriction-Bypass: Unlock Failed, playabilityStatus: AGE_VERIFICATION_REQUIRED
```

**Comment by Marfjeh** [comment]
With ublock origin enabled, its spamming 
```
Simple-YouTube-Age-Restriction-Bypass-Error: DOMException: A network error occurred.
```
in the console.

**Comment by Dyras** [comment]
I can confirm this is an adblock issue. Happening with AdNauseam too

**Comment by mikeloeven** [comment]
I would rather see this fixed user script side last thing anyone wants to do is turn off an ad blocker on you tube XD

**Comment by Dyras** [comment]
@JustOff thanks for the fix in advance. The world is a better place because of people like you.

**Comment by zerodytrash** [comment]
@JustOff thank you for your wonderful fix :)

**Comment by JustOff** [comment]
First of all, thank you for your very useful script! Conflict with uBlock Origin was a serious obstacle to me and I'm glad to share the solution I managed to find.
