### ISSUE TITLE
Script gives TypeError in Safari iPadOS

### ISSUE THREAD

**Issue by VGisHere** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#103]
![Screenshot 2021-12-19 at 2 33 18 PM](https://user-images.githubusercontent.com/25398439/146669453-fedc5325-1774-4d5f-84af-f4d41d2d79b4.png)

**Comment by drunkwinter** [comment]
Hi, what version of Safari and IOS are you on?

**Comment by VGisHere** [comment]
I’m using iPadOS 15.2

**Comment by drunkwinter** [comment]
Could you try this custom build and take a screenshot of the errors in the console again?

[Simple-YouTube-Age-Restriction-Bypass.user.zip](https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/files/7746581/Simple-YouTube-Age-Restriction-Bypass.user.zip)

**Comment by VGisHere** [comment]
Cant spot any info relating to the errors!
![IMG_1391](https://user-images.githubusercontent.com/25398439/146805260-b5c721d0-bac8-45a8-80c0-bbf6c9bec85f.png)

![IMG_1393](https://user-images.githubusercontent.com/25398439/146805275-c2ea6023-f2f1-4345-8e79-20853d41ee4d.png)

**Comment by VGisHere** [comment]
I see something new on refresh.
![IMG_1394](https://user-images.githubusercontent.com/25398439/146806017-02947c35-da16-4459-8883-4162c8d624e2.png)

**Comment by VGisHere** [comment]
![IMG_1395](https://user-images.githubusercontent.com/25398439/146806175-73ad1b26-23c5-4dc8-a872-a4a3a1a1c851.png)

**Comment by drunkwinter** [comment]
This issue seems to be a duplicate.

Merged with 

- #102.
