### ISSUE TITLE
Video description missing

### ISSUE THREAD

**Issue by AndnixSH** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#105]
Video description is not showing due to age restriction.

![image](https://user-images.githubusercontent.com/40742924/147119780-a212d73d-b1d1-447c-ba00-9f7c34babc97.png)

Is it possible to retrieve description?

Video link: `https://www.youtube.com/watch?v=fgYvlz_fdkY`

**Comment by drunkwinter** [comment]
This has already been fixed in 2.2.3, just waiting on the release.

**Comment by AndnixSH** [comment]
oh i just realized i'm using old version 2.1.4. I thought it was updating automatically

After updating to 2.2.2, it works now
