### ISSUE TITLE
Video reloads after ~1 second

### ISSUE THREAD

**Issue by Bec-de-Xorbin** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#113]
Video starts and then reloads after about 1 second of playback and starts over. Seems like an issue with 2.3.2. Version 2.3.1 works ok.

Windows 10, Google Chrome 97.0.4692.71 (Official Build) (64-bit), Tampermonkey v4.13.

**Comment by zerodytrash** [comment]
We are already aware of the problem. It will be fixed in the next release (probably today or tomorrow).

**Comment by zerodytrash** [comment]
The problem should be fixed in the latest version. Maybe you can test it again @Bec-de-Xorbin ?

**Comment by Bec-de-Xorbin** [comment]
Yes, now it works ok. Thank you!
