### ISSUE TITLE
User script crashes during initialization when calling `document.documentElement.append()`

### ISSUE THREAD

**Issue by RomanPlayer22** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#116]
Please do something (Happens on google chrome)

**Comment by zerodytrash** [comment]
I also experienced this problem today. We will investigate...

![image](https://user-images.githubusercontent.com/59258980/150653902-8cc5f1d6-23e5-48c8-968b-5fb1efd1bc9d.png)

**Comment by drunkwinter** [comment]
First time seeing it undefined...

**Comment by zerodytrash** [comment]
This should be fixed. @RomanPlayer22 can you check if it works now.

**Comment by RomanPlayer22** [comment]
Fixed, thanks.
