### ISSUE TITLE
get_video_endpoint always returns 404

### ISSUE THREAD

**Issue by Janisbtw** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#12]
Stopped working for me yesterday, when I opened the dev console, I saw this
![image](https://user-images.githubusercontent.com/35228757/118940828-67ce6080-b951-11eb-8075-fc0cc5e4f4e9.png)

**Comment by InsaanNotFound** [comment]
Same issue here

**Comment by zerodytrash** [comment]
Fixed in the latest version
