### ISSUE TITLE
in play list bypass does not work

### ISSUE THREAD

**Issue by Neon-Ice** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#122]
using firefox & tampermonkey.

**Comment by zerodytrash** [comment]
Can't reproduce. Please provide more info such as exact steps to reproduce and a specific playlist where the problem occurs.
Also make sure you are using the latest version.

Here is a playlist with age restricted videos:
https://www.youtube.com/watch?v=7t0SqerlBA0&list=PLS0s6SV-Psi4uNuM2cIiLGGaHJC7upzOw

**Comment by Neon-Ice** [comment]
It works now. your playlist and mine is also working now.
Thanks for this nice plugin!
