### ISSUE TITLE
No Description

### ISSUE THREAD

**Issue by ThingOfAnimeForever2006** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#124]
help me i can't read me. please help.

**Comment by drunkwinter** [comment]
Confirmed, descriptions seem broken at the moment. But please consider giving us more information next time, like the video URL and the version you tested this on.

**Comment by drunkwinter** [comment]
Fixed in 2.4.2

**Comment by zerodytrash** [comment]
thx @drunkwinter
