### ISSUE TITLE
Video sidebar not working again (Google Chrome issue)

### ISSUE THREAD

**Issue by RomanPlayer22** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#126]
When I try to watch a sample video (How To Make a Rainbow Cake)
When I enter the page, the sidebar loads but when I refresh page, it disappears
Also, can you readd the share option btw (I cant share videos)

**Comment by RomanPlayer22** [comment]
image evidence btw
![Snímek obrazovky 2022-02-18 175434](https://user-images.githubusercontent.com/47942792/154727364-a3b5db74-209f-47b9-8db1-b7f48ec2c43c.jpg)

**Comment by zerodytrash** [comment]
Happens sporadically. Not with every reload. To fix this we need to handle the `continuationEndpoint` and request the `comments-section` via an additional POST request to `/youtubei/v1/next`.

![image](https://user-images.githubusercontent.com/59258980/154735739-17d46b42-33ee-4d87-a36c-b46f2a35d4be.png)

**Comment by zerodytrash** [comment]
nvm my last comment was bullshit. youtube is currently rolling out an update that fixes the `clientScreen:EMBED` bypass. That' s why the watch next feed is sometimes empty.

**Comment by zerodytrash** [comment]
This should now be fixed by implementing the account proxy as a fallback. @RomanPlayer22 check the latest version.
