### ISSUE TITLE
Feature Request: Add functionality for music.youtube.com

### ISSUE THREAD

**Issue by EisigesEis** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#132]
Age Restriction of YouTube also applies to "music.youtube.com". Could you add functionality for that site?

**Comment by drunkwinter** [comment]
YouTube Music is already functioning and is fully supported. Could you be more specific of the functionality you are missing?

**Comment by EisigesEis** [comment]
I was using the newest version of Brave, Tampermonkey and the userscript. I must've done something wrong in my set-up process. The script was only shown as active on youtube.com and not on music.youtube.com. After a Tampermonkey update and re-installing the script it is working on music.youtube.com too.
