### ISSUE TITLE
Simple YouTube Age Restriction Bypass (UserScript) better than Age Restriction Bypass for YouTube™ (extension)

### ISSUE THREAD

**Issue by Cade66** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#136]
I'm using flawlessly the _**Simple YouTube Age Restriction Bypass**_ ver. 2.4.6 UserScript (at Greasemonkey) by _zerodytrash_.
I've just tried the _**Age Restriction Bypass for YouTube™**_ ver. 2.4..6 extension (at AMO) by _zerody_.
I assume developer is the same person.

The extension lacks options available with the userscript.

1-
- The UserScript includes the option;
  `const ENABLE_UNLOCK_CONFIRMATION_EMBED = true;` 
  [Note] When set to _true_ (default), strangely I am **not** asked to confirm the unlock process on YouTube age restricted videos and the video is **not** handled by the script;
  When set to _false_, embedded YouTube age restricted videos **are** handled by the script;
- The extension does not include this option hence is unable, here, to handle embedded videos.

2- 

The UserScript (handled here with ViolentMonkey) allows the user to include other YouTube watch urls such as `https://www.youtube-nocookie.com/`:
  `// @match  https://www.youtube-nocookie.com/* `

Combined (1) and (2) UserScript advantages allow for instance to have `https://www.youtube-nocookie.com/embed/7t0SqerlBA0` handled by the script, whilst this impossible with the extension...

No need to say how much the script is appreciated.
This post to suggest that the extension include the script options in order to allow an as fine-tuning.

Whatever, thanks for both even if, personally, I stick to the script). 

One last word for uBlock Origin users who may need to add to their _My Rules_ (depending on their uBO settings):
```
youtube.com phx.4everproxy.com * noop
youtube.com youtube-proxy.zerody.one * noop
```
and, such as in my case:
```
youtube-nocookie.com phx.4everproxy.com * noop
youtube-nocookie.com youtube-proxy.zerody.one * noop
```
That's about it :=)

**Comment by zerodytrash** [comment]
hi, thanks for pointing that out! Yes, the userscript is definitely better if you want to extend or customize it. The extension is more intended for people who have no knowledge in this field. I will check the strange behavior with `ENABLE_UNLOCK_CONFIRMATION_EMBED`. Possibly there is a logic error. The integration of `www.youtube-nocookie.com` makes totally sense! Never thought about that.

**Comment by zerodytrash** [comment]
The extension has now a settings page!
