### ISSUE TITLE
Publish usercript version on npm

### ISSUE THREAD

**Issue by Araxeus** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#137]
could you publish the script on npm?

could even be the exact same as the userscript here

it would greatly help with keeping it updated

**Comment by drunkwinter** [comment]
I don't really see the use of that, since this is not a importable module/package. Also the userscript manager already automatically keeps you up-to-date. If that's not the case, what manager are you using?

**Comment by zerodytrash** [comment]
@drunkwinter i think it's for use in other projects, like https://github.com/th-ch/youtube-music/commit/23058729f3965deb0bff9b638feb5d419da6e913
The user script can be imported via es6 syntax `import "simple-youtube-age-restriction-bypass"`.

Here we have it: https://www.npmjs.com/package/simple-youtube-age-restriction-bypass

**Comment by drunkwinter** [comment]
@zerodytrash That's weird so it's basically importing code, which you cannot modify or call or initialize?

**Comment by zerodytrash** [comment]
yes, the code is injected directly into the window without any instantiation or function calls. This is unusual for an NPM module. And the execution also works only on the YouTube page. But in some electron apps like https://github.com/th-ch/youtube-music that could work. It is not a big deal to type `npm publish` when publishing a new version.

**Comment by drunkwinter** [comment]
Yeah I can see the use case now ;)

Closing since it looks like it's solved.

> @drunkwinter i think it's for use in other projects, like [th-ch/youtube-music@2305872](https://github.com/th-ch/youtube-music/commit/23058729f3965deb0bff9b638feb5d419da6e913) The user script can be imported via es6 syntax `import "simple-youtube-age-restriction-bypass"`.
> 
> Here we have it: https://www.npmjs.com/package/simple-youtube-age-restriction-bypass

**Comment by Araxeus** [comment]
Wow that was fast, thank you !

Just out of curiosity @zerodytrash how did you figure out this was about https://github.com/th-ch/youtube-music/commit/23058729f3965deb0bff9b638feb5d419da6e913 ?

**Comment by zerodytrash** [comment]
@Araxeus I know the project and yesterday a friend brought the script integration to my attention. Since you had recently contributed to the project, I guessed it had something to do with that :)
