### ISSUE TITLE
[Enhancement] Improve Animation

### ISSUE THREAD

**Issue by bachig26** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#144]
The animations in the toggles, sections like settings, and others to interact with.

I hope these animations are little smoother and faster to use. It's kind of slow with v2.5.1.

**Comment by drunkwinter** [comment]
Do you by any chance mean the height transition? The height transition is indeed really slow in a extension window. I think I'm gonna need to remove the transition and make the height static.

**Comment by bachig26** [comment]
> Do you by any chance mean the height transition? The height transition is indeed really slow in a extension window. I think I'm gonna need to remove the transition and make the height static.

I think so, it is. I don't know the exact technical word.

**Comment by drunkwinter** [comment]
Changed behavior in commit 53d4c45071e7024733f788fb157fa4d3f0c2c5e5.

**Comment by zerodytrash** [comment]
Is that done?

**Comment by drunkwinter** [comment]
Fixed in release [2.5.2](https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/releases/tag/v2.5.2)
