### ISSUE TITLE
Conflict with Blocktube

### ISSUE THREAD

**Issue by Mia872** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#147]
### What happened?

Causes Blocktube to stop functioning, turning userscript off fixes the issue. Not sure if your problem but any help would be appreciated.

Blocktube github page https://github.com/amitbl/blocktube

### Platform

Userscript

### Version

2.5.1

### What browser are you on?

Firefox

### Browser version

102

### About you

- [ ] I am a developer and/or have knowledge in programming

**Comment by drunkwinter** [comment]
@Mia872 Thanks for reporting we will take a look at it.

@zerodytrash Seems like they are using the `defineProperty` function from uBlock origin, which seems pretty good at preventing conflicts. Maybe we should start using that too?

**Comment by drunkwinter** [comment]
@zerodytrash  I think this works?

**Comment by zerodytrash** [comment]
@drunkwinter yes, this works!

**Comment by zerodytrash** [comment]
@Mia872 can you test if the attached userscript version fixes all problems?
[Simple-YouTube-Age-Restriction-Bypass.user.zip](https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/files/9015462/Simple-YouTube-Age-Restriction-Bypass.user.zip)

**Comment by Mia872** [comment]
@zerodytrash yes seems to be working again. Thank you very much
