### ISSUE TITLE
Conflicts/Compatability Issues with BlockTube

### ISSUE THREAD

**Issue by LifeLineRH** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#149]
### What happened?

I'm a Firefox user (currently on Firefox 98), and I've been using your script (through Violentmonkey) in conjunction with [the Firefox/Chrome extension BlockTube](https://github.com/amitbl/blocktube). Now previously, your script and the extension didn't conflict *too* much with one another, but now, recently, they do.

Because both your SYTARB and BlockTube targets the same YouTube code, the former seems to completely break the latter, or vice versa. Starting one video with both on seems to break how recommended videos (including those blocked via BlockTube) appear, including the options you can click on for each video on BlockTube's end, and then starting/going to another video on the same tab seemingly causes it to break - in which the options for the recommended videos don't show the BlockTube-specific options at all.

Although, _yes,_ I can disable your script and then re-enable it when I want to watch a 18+ YouTube video, I... _kinda_ don't want to do that?? (And also, there's a reason I want BlockTube on at all times, as opposed to turning _it_ off instead of SYTARB; let's put it that way.)

I'm not sure how this would or could be resolved or fix, beyond just talking to the creator of BlockTube and collaborating from there if possible. Maybe I should report this on [the BlockTube issues page](https://github.com/amitbl/blocktube/issues) as well?

### Platform

Userscript

### Version

2.5.1

### What browser are you on?

Firefox

### Browser version

Firefox 98

### About you

- [ ] I am a developer and/or have knowledge in programming

**Comment by LifeLineRH** [comment]
Huh. [It seems the issue had already been fixed](https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/issues/147), but the script itself hasn't been updated server-side on GitHub yet. I'll see if [the embedded zip works](https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/issues/147#issuecomment-1170627063) for me.

**Comment by LifeLineRH** [comment]
Hm. Seems to work now. Hope you can add this fix to a proper .js update soon.

**Comment by zerodytrash** [comment]
Still had a few tests pending and now the new version is released which includes the fix: https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/releases/tag/v2.5.2
