### ISSUE TITLE
Doesn't work on this video

### ISSUE THREAD

**Issue by makeworld-the-better-one** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#15]
Taking the video from this youtube-dl issue: https://github.com/ytdl-org/youtube-dl/issues/28578

Video URL is https://www.youtube.com/watch?v=rR8s72aouNE

The script does not work for me on Firefox. Disabling adblockers didn't make a difference.

**Comment by zerodytrash** [comment]
I have tested the video in different download tools and all of them fail. Without a google account the video seems to be unavailable.

playabilityStatus: `LOGIN_REQUIRED`

This is a general problem and I think a fix is not so easy.

**Comment by 89z** [comment]
That video requires authentication, with either OAuth `Authorization` header or `Cookie` headers.

**Comment by zerodytrash** [comment]
Due to the newly implemented account proxy, such videos are now also playable. Let me know if this is not the case.
