### ISSUE TITLE
Not working anymore on iOS 15.6

### ISSUE THREAD

**Issue by anon238** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#151]
I see the banner underneath the page that it’s been unlocked, but the video stays age-locked. It worked before. I tried to disable all other userscripts to check if there is a conflict, but couldn’t find anything.

**Comment by drunkwinter** [comment]
Could you provide the video URL please?

**Comment by anon238** [comment]
Sure, here an example: https://m.youtube.com/watch?v=sGgfZn-Rzxg

**Comment by drunkwinter** [comment]
Is there any way for you to access the console/devtools and take a screenshot of the errors that are possibly produced?

**Comment by anon238** [comment]
```
TypeError {  }
GM_getAllResourceText---- MessageEvent { isTrusted: true }
__resourceTextStroge== null
GM_getAllResourceText---- MessageEvent { isTrusted: true }
__resourceTextStroge== null
[Return YouTube Dislikes] Setting up... 
Simple-YouTube-Age-Restriction-Bypass: Trying Player Unlock Method #2 (TV Embedded Player)
[Return YouTube Dislikes] Registering button listeners... 
[Return YouTube Dislikes] Fetching votes... 
[Return YouTube Dislikes] Received count: 12 
Load failed
Load failed
Load failed
```

**Comment by anon238** [comment]
This is with all extensions turned off:

```
__resourceTextStroge== null
Simple-YouTube-Age-Restriction-Bypass: Trying Player Unlock Method #2 (TV Embedded Player)
[Eruda] Please call "eruda.init()" first
[Eruda] Please call "eruda.init()" first
[Eruda] Please call "eruda.init()" first
[Eruda] Please call "eruda.init()" first
[Eruda] Please call "eruda.init()" first
[Eruda] Please call "eruda.init()" first
[Eruda] Please call "eruda.init()" first
Load failed
Load failed
Load failed
```

**Comment by drunkwinter** [comment]
Is this all? It seems like there is some missing information at the beginning and possibly the end. Wish the used console was more informative ;(

@zerodytrash Any ideas? Could it be a possible race condition again?

**Comment by anon238** [comment]
It was sadly all I could find.

**Comment by zerodytrash** [comment]
Can reproduce that. Seems to be really a race condition that only affects the mobile website. After reloading several times, it works.

![IMG_2082](https://user-images.githubusercontent.com/59258980/184050324-5bc1ca73-ff6a-456c-8bc6-6cc4fb10f501.PNG)

**Comment by drunkwinter** [comment]
Hi, does this issue still occur?

**Comment by drunkwinter** [comment]
Closing this issue for now, since I could not reproduce this on newer versions of IOS.
