### ISSUE TITLE
How can I use this to download videos

### ISSUE THREAD

**Issue by SuperIsakSwahn** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#152]
### What's the problem this feature will solve?

This isn't really a featurerequest but I wanna know how to download agerestricted videos, I have been looking for a while
Is it possible to install this to 4KVideodownloader or freetube or JDownloader?

### Describe the solution you'd like

No bugs

**Comment by D3SOX** [comment]
[yt-dlp](https://github.com/yt-dlp/yt-dlp) works to download age-restricted videos

**Comment by SuperIsakSwahn** [comment]
> I guess just use [yt-dlp](https://github.com/yt-dlp/yt-dlp). It works to download age-restricted videos
Thanks! But i downloaded and ran yt-dlp.exe and it doesnt do anything
Well something pops up then closes before I can read a word

**Comment by SuperIsakSwahn** [comment]
Idk much about this stuff but it looks like the file is broken

**Comment by zerodytrash** [comment]
yt-dlp is a command line tool. You have to run it from the command line and pass the YT video URL as parameter.

**Comment by SuperIsakSwahn** [comment]
Oh I put it in the windows folder and it works now
It warned me about something, then gibberish gibberish, then "ERROR: unable to open for writing: [Errno 13] Permission denied: "'1La4QzGeaaQ.mp4'.part"

**Comment by SuperIsakSwahn** [comment]
Oh I tried restarting cmd and running the command and it looks like it works now?

**Comment by SuperIsakSwahn** [comment]
Thanks! Could you tell me where downloaded files are? I thought it was gonna be in my userfolder but doesn't seem like that

**Comment by D3SOX** [comment]
Maybe try a GUI for it if you're not familiar with the command line
For example https://github.com/axcore/tartube

**Comment by SuperIsakSwahn** [comment]
> Maybe try a GUI for it if you're not familiar with the command line For example https://github.com/axcore/tartube

I figured out how to use it now but thanks!

**Comment by Curve** [comment]
> Thanks! Could you tell me where downloaded files are? I thought it was gonna be in my userfolder but doesn't seem like that

It's in the same folder you executed the command from

**Comment by drunkwinter** [comment]
You also might try this, if you want to download it via YT directly, it's compatible with this bypass.

https://greasyfork.org/en/scripts/369400-local-youtube-downloader
