### ISSUE TITLE
Prevent it from removing videos on the side?

### ISSUE THREAD

**Issue by Arndorferd** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#16]
Videos on the side are removed on restricted videos can they be added back? This [script](https://greasyfork.org/en/scripts/375525-youtube-age-verification-bypass) blocks the videos without removing the side but it has a delay, yours doesn't have a delay, if you could add them back without the delay it would be seamless.

**Comment by zerodytrash** [comment]
The video recommendations are retrieved via the `/youtubei/v1/next` endpoint. It seems that the same age-gate bypass (`clientScreen`:`EMBED`) can be used as for the `/youtubei/v1/player` endpoint...
