### ISSUE TITLE
second scrollbar randomly appear and disappear

### ISSUE THREAD

**Issue by braisiak** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#160]
### What happened?

When I watched age restricted video on youtube (Firefox) second scrollbar randomly appeared and disappeared.

### Platform

Extension

### Version

2.5.2

### What browser are you on?

Firefox

### Browser version

105.0.3

### About you

- [ ] I am a developer and/or have knowledge in programming

**Comment by drunkwinter** [comment]
Hi, without screenshots, videos or any explanation as to how to trigger the bug, we cannot reproduce and therefore can't fix it.

Please provide more information and confirm you have all other extensions disabled.
