### ISSUE TITLE
Video thumbnails do not unblur again

### ISSUE THREAD

**Issue by DynamoMotor32** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#164]
### What happened?

Video thumbnails do not unblur again.

The Youtube Short video thumbnails didn't unblur either before the regular video thumbnails stopped to unblur.

Present on the current latest version [v2.5.3](https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/releases/tag/v2.5.3)

### Platform

Userscript

### Version

v2.5.3

### What browser are you on?

Chrome

### Browser version

-

### About you

- [X] I am a developer and/or have knowledge in programming

**Comment by drunkwinter** [comment]
Working on it.

**Comment by drunkwinter** [comment]
Fixed in latest commit and will be included in `2.5.4`.

@zerodytrash Needs release.

**Comment by zerodytrash** [comment]
Done. https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/releases/tag/v2.5.4

**Comment by THEtomaso** [comment]
Thumbnails are blurred, yet again. :(

**Comment by drunkwinter** [comment]
> Thumbnails are blurred, yet again. :( _(Using v2.5.4 in LibreWolf [Firefox fork])_

It still seems to work for me. Please make a new bug report.
