### ISSUE TITLE
not unblocking any video

### ISSUE THREAD

**Issue by wearerofpinkhoodies** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#165]
### What happened?

when i try to watch an age restricted video it doesn't unblock, I checked with multiple age restricted videos and none of them worked.  i tried to see if the problem was caused by other extensions but the problem persisted.  

### Platform

Userscript

### Version

2.5.4

### What browser are you on?

Chrome

### Browser version

107.0.5304.107

### About you

- [ ] I am a developer and/or have knowledge in programming

**Comment by drunkwinter** [comment]
Could you paste the log of the developer console or make a screenshot of it? Make sure you are on the restricted video page first.

You can access the developer console by pressing F12 on your keyboard. Everything labeled `Simple-YouTube-Age-Restriction-Bypass` is relevant.

**Comment by wearerofpinkhoodies** [comment]
this is what the console shows
![errors](https://user-images.githubusercontent.com/118110908/201528084-55d688b0-dc1d-43a3-8ded-c282f2c2740f.png)

**Comment by drunkwinter** [comment]
I see nothing related too `Simple-YouTube-Age-Restriction-Bypass` here. Maybe you forgot to scroll up? It also could be that the userscript is disabled for some reason? You said you tried without extensions, but did you also disable all userscripts to see if there are any conflicts?

**Comment by wearerofpinkhoodies** [comment]
Simple-YouTube-Age-Restriction-Bypass is enabled and it's the only userscript that is enabled. I can't find anything related to Simple-YouTube-Age-Restriction-Bypass on the log

**Comment by wearerofpinkhoodies** [comment]
im currently using tampermonkey, now i'll try to use another one to see if it works

**Comment by wearerofpinkhoodies** [comment]
using violentmonkey solved the problem, now it works on any video i tried. thanks for the help

**Comment by drunkwinter** [comment]
That's very interesting.. May I ask what version of Tampermonkey you were using?

**Comment by wearerofpinkhoodies** [comment]
i was using version 4.18.0

**Comment by drunkwinter** [comment]
I have tried it with Tampermonkey and everything went just fine, so I don't know what went wrong here.

But I'm glad you still got it working.
