### ISSUE TITLE
Telling us what video to watch next and the description of the video not showing up.

### ISSUE THREAD

**Issue by Jamesgsburns** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#167]
### What happened?

I can watch the videos but telling us what video you want to watch next (the videos on the right on desktop) and the description of the videos are not showing up.

### Platform

Userscript

### Version

2.5.4

### What browser are you on?

Chrome

### Browser version

4.18.1

### Link to the video

https://www.youtube.com/watch?v=-Tp87ljsNAA

### Screenshots or Videos

![Capture](https://user-images.githubusercontent.com/121324756/209439099-d3bb9fb4-3414-405e-ac47-9996b308f1f9.PNG)

### About you

- [ ] I am a developer and/or have knowledge in programming

**Comment by drunkwinter** [comment]
Hi, thanks for reporting.

YouTube made some server-side changes which broke things on our end. The issue has been fixed and should hopefully be live within couple days. You don't have to do anything since this will be a server-side update.

We'll close this issue as soon as the fix is live.

**Comment by Jamesgsburns** [comment]
Thanks for the completion also do you think you can make all the age restricted videos show up in search results? It will be easier to look for the videos you're looking for, it's fine with me if it doesn't work or takes a while.

**Comment by drunkwinter** [comment]
> Thanks for the completion also do you think you can make all the age restricted videos show up in search results? It will be easier to look for the videos you're looking for, it's fine with me if it doesn't work or takes a while.

I don't think it's possible, because there is no way to get the unrestricted data. But feel free to file a feature request anyway.
