### ISSUE TITLE
Add it to Youtube Revanced

### ISSUE THREAD

**Issue by YT-Advanced** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#171]
### What's the problem this feature will solve?

Dear sir, I love your age restriction bypass but can you add it to Youtube Revanced

### Describe the solution you'd like

Like title

**Comment by BlueStarBRS** [comment]
i hope he will add it

**Comment by drunkwinter** [comment]
Sorry guys, we are not related to the ReVanced people and are not familiar at all with their codebase, let alone the languages (Kotlin/Java) and tools they use.

I completely agree with you on the issue (I use their app as well), but this has to be brought up with the developers of ReVanced. The place to do that is probably here https://github.com/revanced/revanced-patches.
