### ISSUE TITLE
[firefox] [extension] Video thumbnails do not unblur again - Follow up

### ISSUE THREAD

**Issue by THEtomaso** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#172]
### What happened?

Reference:
https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/issues/164#issuecomment-1368452408

I've researched this further now..

As I'm sure you know; everyone aren't served the same changes to YouTube simultaneously.
It depends on your regional location, amongst other things.

For me (who's located in Norway), the thumnails are blurred when using Age Restriction Bypass for YouTube v2.5.4.
Going back to v2.5.3 fixes the issue!

### Platform

Extension

### Version

v2.5.3 / v2.5.4

### What browser are you on?

Other (mention below with version)

### Browser version

LibreWolf v108.0.1-1 (x64) (Tracking Protection = Standard)

### About you

- [ ] I am a developer and/or have knowledge in programming

**Comment by drunkwinter** [comment]
Is there any way you could get me the image url of these blurred thumbnails? Right mouse click on the thumbnail and copy image address should do.

**Comment by THEtomaso** [comment]
Sure, here you go..

### Using Age Restriction Bypass for YouTube v2.5.3:
![AgeRestrictionBypassForYouTube-BlurredImages-1](https://user-images.githubusercontent.com/9382674/210401358-83c8c6a1-e6bc-4c17-ae18-b00a87efd9c2.jpg)

--

### Using Age Restriction Bypass for YouTube v2.5.4:
![AgeRestrictionBypassForYouTube-BlurredImages-2](https://user-images.githubusercontent.com/9382674/210401399-e83118f8-c083-4ece-a9b7-d319389d440a.jpg)

**Comment by drunkwinter** [comment]
Alright, apparently this is some other issue than just thumbnails that needs to be fixed. As a workaround you can temporarily use the userscript version.

**Comment by THEtomaso** [comment]
> As a workaround you can temporarily use the userscript version.

No need.
The extension v2.5.3 works just fine, like I pointed out. :)

**Comment by drunkwinter** [comment]
> > As a workaround you can temporarily use the userscript version.
> 
> No need. The extension v2.5.3 works just fine, like I pointed out. :)
> 
> --
> 
> **EDIT:** Alternatively, this also works for me, in uBlock Origin: `||ytimg.com^$removeparam=sqp` ..but I'm uncertain as to whether or not it might cause any side effects.

Nope that is kind of what we do. But the only downside doing it this way is performance. By removing the `sqp` parameter for all images, you cause all thumbnails to load at the highest resolution and possibly twice (not sure).  We only remove the `sqp` parameter if the length is a specific size, meaning it's blurred.

**Comment by drunkwinter** [comment]
Also version `2.5.3` does not detect all blurred thumbnails.

**Comment by THEtomaso** [comment]
OK, I'm sure you'll be able to come up with a proper fix. :)

**Comment by drunkwinter** [comment]
@zerodytrash Needs release.

**Comment by THEtomaso** [comment]
> Needs release.

Perhaps even a fork, it would seem..

**Comment by THEtomaso** [comment]
Yeah, I noticed that.
I've switched to the userscript version for now, and it works just fine! :)

**Comment by drunkwinter** [comment]
Fix for the thumbnail issue landed in [2.5.5](https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/releases/tag/v2.5.5). 

Will have a look at a better way to do a manual install, when I got some time.
