### ISSUE TITLE
[Tampermonkey] Bypass not working

### ISSUE THREAD

**Issue by flappix** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#178]
### What happened?

Hi,
2-3 days ago the script stopped working. Before I was using it for a long time without problems.
Now I see the the request from YouTube to sign in and see blurry thumbnails of age restricted videos. Actually the same behavior like not using the script at all.

Browser: Chromium Version 108.0.5359.124 (Official Build) Arch Linux (64-bit)
Tampermonkey: 4.18.1
Simple-YouTube-Age-Restriction-Bypass: 2.5.4

### Platform

Userscript

### Version

2.5.4

### What browser are you on?

Chrome

### Browser version

108.0.5359.124

### About you

- [X] I am a developer and/or have knowledge in programming

**Comment by drunkwinter** [comment]
This seems like an issue related to Tampermonkey, they however seem to claim it's a chromium bug.

Follow these steps listed at https://www.tampermonkey.net/faq.php#Q208:

> A208 This is caused by a bug in Chromium that causes Tampermonkey's content scripts to run in the wrong order. Unfortunately the order matters and due to timing constraints it is not possible to wait longer for the other content script than already done. This bug "only" happens when the extension is updated from a previous stable version lower than 4.18. To fix the issue simply:
> 
> - Disable Tampermonkey extension
> - Restart browser (make sure that all browser processes are gone, better restart the computer)
> - Enable Tampermonkey extension
> - Restart browser
> 
> Disabling the extension seems to cleanup things and the content scripts are executed in the right order again.
> 
> If it still doesn't work, then please
> 
> - export your settings and scripts (you can try importing them into the BETA version first to be on the safe side) and
> - re-install Tampermonkey and
> - import the backup again.

If you still encounter the same issues try switching to [Violentmonkey](https://violentmonkey.github.io).

**Comment by flappix** [comment]
Thanks for fast answering. Reinstalling Tampermonkey solved the issue indeed.
