### ISSUE TITLE
script no longer works? 

### ISSUE THREAD

**Issue by Incineratinq** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#18]
just minutes ago i watched an age restricted video with the script enabled with Tampermonkey in Firefox. i opened another video in a new tab and tried watching it, now i get the same old verify age prompt. i then tried it on vivaldi which is my main browser, which has been working with no issues for a month or so, and neither video works there either.

**Comment by Denton0451** [comment]
Same here

**Comment by gatosyperros** [comment]
same here worked last night, but today it's not working.

**Comment by Ambyjkl** [comment]
Youtube seems to have apparently patched out the `/get_video_info` endpoint. The following returns a 404: https://www.youtube.com/get_video_info?video_id=fJr7Ph5SGO4

**Comment by oneandonlyjason** [comment]
Youtube seems to kill the Endpoint right now. Sometimes the Endpoint is working and sometimes not.

See also: https://github.com/ytdl-org/youtube-dl/issues/29086#issuecomment-862582324

**Comment by zerodytrash** [comment]
> Youtube seems to have apparently patched out the `/get_video_info` endpoint. The following returns a 404: https://www.youtube.com/get_video_info?video_id=fJr7Ph5SGO4

Works for me when i add the `&html5=1` param.
https://www.youtube.com/get_video_info?video_id=fJr7Ph5SGO4&html5=1

But sometimes I also get a 404 error. Very strange...

**Comment by oneandonlyjason** [comment]
In the Linked Thread they added a few more Informations that also seem to say that youtube is shutting this api Endpoint Down

**Comment by zerodytrash** [comment]
> Youtube seems to kill the Endpoint right now. Sometimes the Endpoint is working and sometimes not.
> 
> See also: [ytdl-org/youtube-dl#29086 (comment)](https://github.com/ytdl-org/youtube-dl/issues/29086#issuecomment-862582324)

That would be a pity. I don't know any alternative.

**Comment by Atervanda** [comment]
At the risk of jinxing it: the script is working for me now (you may need to clear cookies), even though it wasn't an hour ago and no changes appear to have been made. Odd? The `/get_video_info` link still returns a 404.

**Comment by dubesor** [comment]
Not working on FF, tried this video

https://www.youtube.com/watch?v=dJwjqZZgcWk

Private window: same result, disabled ublock origin: same result. Signed in: Verify your age, Signed out: Sign in to confirm your age

**Comment by MikeTester21** [comment]
same here, it just stopped working, html5=1 is not working anymore. It was still working few hours ago. 

So do we have any way at all to get the url of video or download (with YT script or any other way) protected videos or not anymore?

**Comment by VanHoevenTR** [comment]
Same, not working for me too

**Comment by VindicatorHQ** [comment]
Stopped working on Chrome for me

**Comment by zerodytrash** [comment]
I've added two more parameters (`&c=TVHTML5&cver=7.20190319`) to the `/get_video_info` endpoint. 
Now it seems to work again. Can someone confirm this?

https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/commit/5abba9eb18ce1fd1265f97548e06b7c9d7652ce0

Successfully tested with: 
https://www.youtube.com/watch?v=fJr7Ph5SGO4
https://www.youtube.com/watch?v=duZsTr6_-mg

**Comment by VindicatorHQ** [comment]
Can confirm that it worked for me, thanks!

**Comment by grysor** [comment]
> 
> 
> I've added two more parameters (`&c=TVHTML5&cver=7.20190319`) to the `/get_video_info` endpoint.
> Now it seems to work again. Can someone confirm this?
> 
> [5abba9e](https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/commit/5abba9eb18ce1fd1265f97548e06b7c9d7652ce0)
> 
> Successfully tested with:
> https://www.youtube.com/watch?v=fJr7Ph5SGO4
> https://www.youtube.com/watch?v=duZsTr6_-mg

It works for me too, a huge thank you from france for your work ! 👍 😛😃🎉🎉

**Comment by AndnixSH** [comment]
Works for me too! Thanks for your hard work!

**Comment by Celuni** [comment]
Although it works, it doesn't work with Ublock easylist for some reason.

**Comment by gatosyperros** [comment]
> I've added two more parameters (`&c=TVHTML5&cver=7.20190319`) to the `/get_video_info` endpoint.
it seems to work, it works with Ublock, NoScript, SponsorBlock, Adblock

**Comment by Useless-Panda** [comment]
works for me with Ublock

**Comment by p3k22** [comment]
Works as described for me with Ublock. Thank you @zerodytrash

**Comment by zerodytrash** [comment]
We close the issue. If it breaks again simply open a new issue 😂
