### ISSUE TITLE
[Enhancement] Add script icon to userscript header

### ISSUE THREAD

**Issue by ae5960e8-a6fc-491f-b252-898ecf59af95** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#180]
### What's the problem this feature will solve?

The line below can be added to the // ==UserScript== area so the logo of the script shows up in our script manages. I suggest using the logo for the project here.

### Describe the solution you'd like

Example from another project:
// @icon https://raw.githubusercontent.com/DenverCoder1/Unedit-for-Reddit/3.9.4/images/logo128.png

### Additional context

As you can see, many other scrips take advantage of this feature, and it would make a good addition.
![](https://user-images.githubusercontent.com/76442625/214338736-2d1e8783-e659-4a0f-989f-c5d8f743b8a8.png)

**Comment by drunkwinter** [comment]
Thanks for the suggestion. Will be there in the next release.
