### ISSUE TITLE
[firefox] Addon can't be installed because it's not signed

### ISSUE THREAD

**Issue by Encore5808** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#182]
### What happened?

Pretty self explainatory. I even set  xpinstall.signatures.required to false, but it doesn't work.

### Platform

Extension

### Version

2.5.4

### What browser are you on?

Firefox

### Browser version

110.0.1

### Screenshots or Videos

![Screenshot (1)](https://user-images.githubusercontent.com/125306042/224051530-d73e74b7-8425-466a-9b80-11e9a6ed15df.png)

### About you

- [ ] I am a developer and/or have knowledge in programming

**Comment by drunkwinter** [comment]
We are aware of this.

You can for now install the unsigned extension by going to `about:addons` choosing `Install Add-on from file`.

**Comment by drunkwinter** [comment]
You possibly have to set `xpinstall.signatures.required` to `true` after installing, so it stays installed even after restart. if that doesn’t work the only option is to use `about:debugging` and install the extension each time you start the browser, which i doubt you want to do.

You can still always install the userscript, till we have sorted this out.

**Comment by drunkwinter** [comment]
See https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/issues/188#issuecomment-1571212232
