### ISSUE TITLE
[Firefox] Cannot manually install/update (add-on not signed)

### ISSUE THREAD

**Issue by BillyJoeJimBob** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#188]
Previous version 2.54 installed from AMO still works but I am not able to manually install v2.5.5 in Firefox 113.0.2 because it is not verified, even with xpinstall.signatures.required set to "false", I get the following popup:        
<img width="416" alt="Screen Shot 2023-05-31 at 12 33 58 PM" src="https://user-images.githubusercontent.com/11702508/242394292-6607befb-7ba1-4b6d-aceb-7d55c5880243.png">
    We are aware of this.

You can for now install the unsigned extension by going to `about:addons` choosing `Install Add-on from file`.

_Originally posted by @drunkwinter in https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/issues/182#issuecomment-1464077159_

**Comment by drunkwinter** [comment]
Previous information I gave was inaccurate,  because I was used to testing the development builds through `about:addons` > `Manage Your Extensions` > `Debug Add-ons`.

Unfortunately, you will need to use an [unbranded build](https://wiki.mozilla.org/Addons/Extension_Signing#Unbranded_Builds), [development build](https://www.mozilla.org/firefox/developer/) or another browser based on Firefox (Pale Moon, Waterfox, etc.) to install unsigned extensions.

We can not do anything about this issue, since our add-on got removed from [addons.mozilla.org](https://addons.mozilla.org) and therefore we are also unable to sign the add-on for self distribution.

I will make sure to update the `README` soon to reflect that we don't support Firefox Stable anymore.

**Comment by BillyJoeJimBob** [comment]
Thank you for you assistance on this!  The old AMO v2.54 and current v2.55 userscript both function as expected. In a probably apples to oranges comparison, I was somehow able to install another extension `Bypass Paywalls Clean` that was also removed from [addons.mozilla.org](url) earlier this year using `about:addons`  > `Install Add-on from file` to install an .xpi file.  see: [https://gitlab.com/magnolia1234/bypass-paywalls-firefox-clean/-/releases](url). I've been using that unsigned extension for a few months and It even self updates but I assume there is some security risk there.

**Comment by drunkwinter** [comment]
@BillyJoeJimBob 
> Thank you for you assistance on this! The old AMO v2.54 and current v2.55 userscript both function as expected. In a probably apples to oranges comparison, I was somehow able to install another extension Bypass Paywalls Clean that was removed from [addons.mozilla.org](https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/issues/url) earlier this year using about:addons > Install Add-on from file to install an .xpi file. see: [https://gitlab.com/magnolia1234/bypass-paywalls-firefox-clean/-/releases](https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/issues/url). I've been using that unsigned extension in Firefox stable for a few months and It even self updates but I assume there is some security risk there.

Yes, I have seen some extensions do this. But those extensions submitted for signing are still being reviewed by the AMO team and are still subject to the same policies. I don't know if doing this is a smart move, but we will look into it.

**Comment by krystian3w** [comment]
Possible modify Firefox Stable to run that script:

https://stackoverflow.com/a/42403531 (Or something similar with an update for Firefox 115+ and 123+ - Somewhere on stackoverflow I mentioned updating for Firefox 78, probably in another question)

Legacy mod: https://github.com/xiaoxiaoflood/firefox-scripts

Aris mod: https://github.com/Aris-t2/CustomJSforFx

MrOtherGuy mod: https://github.com/MrOtherGuy/fx-autoconfig
