### ISSUE TITLE
Doesnt work when logged in

### ISSUE THREAD

**Issue by gamerpaddy** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#19]
When im logged into my youtube account it wont play age restricted videos. 
it will play them in a private window on the other hand

any way to fix this?

**Comment by zerodytrash** [comment]
What message do you receive? Is the parental control active in your account?

**Comment by gamerpaddy** [comment]
None, and no parental control active.

It seems to be related to #18 now with the update it seems to work fine again, both logged in and out. 
couldnt find a video yet that doesnt work yet.
