### ISSUE TITLE
Selecting age-restricted video mostly goes wrong.

### ISSUE THREAD

**Issue by Jamesgsburns** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#191]
### What happened?

The videos mostly won't play unless you refresh and it's annoying.
Edit: It actually happens every time you go to a channel and select it but it works when you go to it with a link through something like your history and you don't have to refresh.

### Platform

Userscript

### Version

v2.5.6

### What browser are you on?

Chrome

### Browser version

Present

### Screenshots or Videos
![](https://github-production-user-asset-6210df.s3.amazonaws.com/121324756/248482796-96730c26-3699-4553-ad8a-e43708926944.png)

### About you

- [ ] I am a developer and/or have knowledge in programming

**Comment by drunkwinter** [comment]
Was able to reproduce.

**Comment by drunkwinter** [comment]
Does this build fix the issue?
- [Simple-YouTube-Age-Restriction-Bypass.user.js.txt](https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/files/11889589/Simple-YouTube-Age-Restriction-Bypass.user.js.txt)

**Comment by Jamesgsburns** [comment]
That build did fix the issue. Nice 👍

**Comment by drunkwinter** [comment]
Fixed in [v2.5.7](https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/releases/tag/v2.5.7).
