### ISSUE TITLE
Doesn't fully work anymore

### ISSUE THREAD

**Issue by zalien63** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#197]
### What happened?

On the first try, the video and audio don't work. When i click on the retry button, only the audio work.

error message:
->An error has occurred. Please retry later.
                         282054944

### Platform

Extension

### Version

2.4.6

### What browser are you on?

Edge

### Browser version

115.0.1901.183

### Link to the video

https://www.youtube.com/watch?v=ReVn9HB4U_Q

### About you

- [ ] I am a developer and/or have knowledge in programming

**Comment by drunkwinter** [comment]
Hi, this issue was fixed with [v2.5.7](https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/releases/tag/v2.5.7). 

Unfortunately the extension got removed from Edge Add-ons, so only a manual install is possible.

**Comment by zalien63** [comment]
thank you very much
