### ISSUE TITLE
Plugin not working: "Something went wrong. Please try again later"

### ISSUE THREAD

**Issue by jhaber1** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#201]
### What happened?

I go to open an age-gated video in a new tab and it displays what's in the attached screenshot in the video pane. I opened it up in a Private Window with just Tampermonkey (v4.19.0) and the script enabled and still get same error. Pressing Retry just reloads the page with the problem persisting.

Win10 Education 21H2

### Platform

Userscript

### Version

2.1.4

### What browser are you on?

Firefox

### Browser version

115.0.3

### Link to the video

https://www.youtube.com/watch?v=E2NGxrGRwmI

### Screenshots or Videos

![Screenshot 2023-08-01 095255](https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/assets/1771146/f004bf18-37aa-4a16-b1c3-940dc7704346)

### About you

- [X] I am a developer and/or have knowledge in programming

**Comment by jhaber1** [comment]
Just delete issue, my bad...

**Comment by EchoDev** [comment]
Looks like Youtube is messing with some things.

Add the following line to your ad blocker and it should work fine again

youtube.com###error-screen
