### ISSUE TITLE
Some videos fail to unlock with `An error occurred. Please try again later. (Playback ID: XP4HKqZPtZSG9lhL)`

### ISSUE THREAD

**Issue by drunkwinter** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#202]
>I'm getting `An error occurred. Please try again later. (Playback ID: XP4HKqZPtZSG9lhL)` , userscript 2.5.7, here's a video link: https://www.youtube.com/watch?v=LvEDqZ75P4c

_Originally posted by @girlmaya in https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/issues/198#issuecomment-1666506790_

**Comment by zerodytrash** [comment]
![image](https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/assets/59258980/0ae19b95-2c39-4eca-a73b-a0dfece95f63)

https://phx.4everproxy.com/ is down :(

**Comment by zerodytrash** [comment]
Means all videos with GCR flag can not be played at the moment.

**Comment by zerodytrash** [comment]
We can switch to https://lv.4everproxy.com/

**Comment by drunkwinter** [comment]
> Means all videos with GCR flag can not be played at the moment.

Yes the URL is just outdated, was gonna patch this.

**Comment by drunkwinter** [comment]
> We can switch to https://lv.4everproxy.com/

I tested `ny`, it works fine too. I guess we should pick the one with lower latency to EU?

**Comment by zerodytrash** [comment]
> I guess we should pick the one with lower latency to EU?

Yes, would make sense.

**Comment by drunkwinter** [comment]
Thanks for reporting @girlmaya.

Fixed in [v2.5.8](https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/releases/tag/v2.5.8).
