### ISSUE TITLE
[th-ch/youtube-music] Cover being black all the time

### ISSUE THREAD

**Issue by MiepHD** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#209]
### What happened?

The video or album cover is always black if the bypass gets injected too early. If imported instantly this problem appears and if you wait until the music is loaded it works for most cases but if the app is started with a protected video you get a warning message that you can never leave.
We use an electron environment (https://github.com/th-ch/youtube-music/issues/1177) and attach the bypass as a preload script. When can we safely inject the bypass to avoid issues?

Note: 2.5.4 is the version we use but the same problem persists in 2.5.9

### Platform

Electron

### Version

2.5.9

### What browser are you on?

Chrome

### Browser version

108.0.5359.215

### About you

- [X] I am a developer and/or have knowledge in programming

**Comment by drunkwinter** [comment]
Hi, that's really weird.. I don't see how injecting early could cause such a problem. Usually something like that happens when injection is late, because by that time our interceptors would have missed the important data to trigger the bypass.

Does this also happen with normal videos which aren't restricted, how can I test this?

**Comment by MiepHD** [comment]
Yeah, it happens with all videos. You can test it by downloading the latest release and enabling the age-restriction-bypass on the top left. After that you may need to restart the app.
https://github.com/th-ch/youtube-music/releases/tag/v1.20.0

**Comment by drunkwinter** [comment]
You guys should be able to fix this by commenting out this line in a separate fork:
https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/blob/4c5c61ac73811217a6402e3860591d28d9968d1e/src/main.js#L10C2-L10C2

Removing the line above shouldn't have any impact on the functionality of the age bypass on YT Music. 

The actual bug occurs in the function `interceptObjectProperty`, only on Electron and I don't know why. With a big refactor coming up soon, this hacky function won't be used anyway, so it's not worth spending time fixing it.

I'll update this issue when the refactor is done so you guys can drop the fork.
