### ISSUE TITLE
Black screen after bypassing, can still hear audio

### ISSUE THREAD

**Issue by blehblehbleh674** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#210]
### What happened?

This black screen appears that says "Something went wrong" every single time I try and view an age restricted video, I can still hear audio, even if I refresh the page it continues

### Platform

Extension

### Version

2.5.6

### What browser are you on?

Chrome

### Browser version

115.0.5790.171

### Link to the video

https://www.youtube.com/watch?v=LMuPiZMaA5A

### Screenshots or Videos

![bug](https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/assets/142314565/82968c5c-7bd1-425f-98b9-97f41b50683a)

### About you

- [ ] I am a developer and/or have knowledge in programming

**Comment by drunkwinter** [comment]
Hi, this issue is fixed in later versions. Please update to [v2.5.9](https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/releases/tag/v2.5.9).
