### ISSUE TITLE
1 issue in debug log

### ISSUE THREAD

**Issue by omboybread** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#211]
# Description
[Please explain the problem/bug/behavior]

# Log
```
14:19:33 [INFO] playerResponse property set, contains sidebar: false
14:19:34 [INFO] playerResponse property set, contains sidebar: false
14:19:34 [INFO] playerResponse property set, contains sidebar: false
14:19:39 [INFO] playerResponse property set, contains sidebar: false
14:19:44 [INFO] playerResponse property set, contains sidebar: false
14:19:46 [INFO] playerResponse property set, contains sidebar: false
14:19:48 [INFO] playerResponse property set, contains sidebar: false
14:19:48 [INFO] playerResponse property set, contains sidebar: false
14:19:50 [INFO] playerResponse property set, contains sidebar: false
14:19:53 [INFO] playerResponse property set, contains sidebar: false
14:19:55 [INFO] Script injected (https://www.youtube.com/watch?v=x9Ak32C5oL8)
14:19:56 [INFO] playerResponse property set, contains sidebar: false
14:19:56 [INFO] playerResponse property set, contains sidebar: false
14:19:57 [INFO] playerResponse property set, contains sidebar: false
14:19:57 [INFO] playerResponse property set, contains sidebar: false
14:19:57 [INFO] playerResponse property set, contains sidebar: false
14:19:57 [INFO] playerResponse property set, contains sidebar: false
14:20:44 [INFO] playerResponse property set, contains sidebar: true
14:20:45 [INFO] playerResponse property set, contains sidebar: false
16:06:37 [INFO] Script injected (https://www.youtube.com/shorts/5QbcCFgVLUc?feature=share)
16:06:38 [INFO] playerResponse property set, contains sidebar: false
16:06:39 [INFO] playerResponse property set, contains sidebar: true
16:06:39 [INFO] playerResponse property set, contains sidebar: false
16:06:41 [INFO] playerResponse property set, contains sidebar: false
16:18:48 [INFO] Script injected (https://www.youtube.com/shorts/m0JK2z4QKr0?feature=share)
16:18:49 [INFO] playerResponse property set, contains sidebar: false
16:18:49 [INFO] playerResponse property set, contains sidebar: true
16:18:49 [INFO] playerResponse property set, contains sidebar: false
16:18:52 [INFO] playerResponse property set, contains sidebar: false

```

**Comment by omboybread** [comment]
> What is the issue?

It says "Something went wrong.Please try again later."

And it gave me this number below: 282054944

Srry for the late reply

**Comment by drunkwinter** [comment]
@omboybread You are probably using an older version. Please update to [v2.5.9](https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/releases/tag/v2.5.9).

Could you give us an update if that works?

**Comment by omboybread** [comment]
How do I update? I`m using it as an extension in Firefox, but when i check for updates it says there are none. When I checked it out I realized (just now) that it wasn't updating. I'm using 2.5.4.

**Comment by drunkwinter** [comment]
From issue #188:
> Unfortunately, you will need to use an [unbranded build](https://wiki.mozilla.org/Addons/Extension_Signing#Unbranded_Builds), [development build](https://www.mozilla.org/firefox/developer/) or another browser based on Firefox (Pale Moon, Waterfox, etc.) to install unsigned extensions.
> 
> We can not do anything about this issue, since our add-on got removed from [addons.mozilla.org](https://addons.mozilla.org/) and therefore we are also unable to sign the add-on for self distribution.

The install process in chromium based browsers is easy on the other hand and can be done by just enabling developer mode. On the other hand if you don't want to bother with this stuff, you can also use our Userscript, which supports auto-update.
