### ISSUE TITLE
Help how do i use?

### ISSUE THREAD

**Issue by S-dot-glitch** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#214]
### What happened?

Hi sry to bother u but could u pls explain to me how to use youre script bc I don't understand how to use it I installed it with tapermonkey and after that the website gave me the code or the script but I'm asking what do I do now

### Platform

Extension

### Version

2.5.9

### What browser are you on?

Chrome

### Browser version

116.0.5845.114

### Screenshots or Videos

![Screenshot_20230830_032401_Chrome](https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/assets/128146014/2fc863fd-26de-45e1-ba0c-8666fbfa80f4)
That's what I see

### About you

- [ ] I am a developer and/or have knowledge in programming

**Comment by S-dot-glitch** [comment]
What do I do now ?

**Comment by drunkwinter** [comment]
Hi, how did you install Tampermonkey on chrome mobile?

Please follow the written instructions here: https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass#android
