### ISSUE TITLE
Doesn't work on Bangkok 112 youtube channel

### ISSUE THREAD

**Issue by Telmesomething** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#219]
### What happened?

The Age Restriction bypass app doesn't work on a youtube channel called Bangkok 112 which is a Members Only channel. But I don't want to sign up to Google just to watch videos on there without knowing what they contain. I don't expect them to be porn in any event. 

The user that created the channel has his own site at https://bangkok112.com/ Scroll down to the first link entitled "What happened to the Bangkok 112 channel" to get background info. 

I didn't try the script/app on the Floorp browser which I'm using to write this report since it's not listed as being supported. Floorp is a Japanese browser created by Ablaze.

### Platform

Userscript

### Version

2.5.9

### What browser are you on?

Firefox

### Browser version

115.3.1esr

### Link to the video

https://www.youtube.com/watch?v=Z8AGEbxAd_M&list=UUMOjPicZ6G9hkBrGTAa4gUfdw&index=2

### About you

- [ ] I am a developer and/or have knowledge in programming

**Comment by drunkwinter** [comment]
Hi, we only bypass public age-restricted video's. That means no private or paid content, and I don't think it's even possible to do so.

**Comment by Telmesomething** [comment]
> Hi, we only bypass public age-restricted video's. That means no private or paid content, and I don't think it's even possible to do so.

OK, thanks for the response anyway.
