### ISSUE TITLE
[Documentation] Would it be possible to add a short explanation how it works?

### ISSUE THREAD

**Issue by rubyFeedback** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#22]
Hey there,

Would it be possible to add a short explanation how it works? It does not have to be
long, just mostly a summary, perhaps one or two points to the code.

Background: I am having a hard time with google lately age-gating everything
including the "you are from europe so we use the data privacy laws against
you and censor you", so I'd love to get around this stream of censorship 
restrictions. But I don't fully understand how this all works; even youtube-dl
throws similar errors, so anything that helps me understand it, would be
super-helpful. And perhaps others may also benefit from a short explanation
if you ever have the time for this. Thank you for reading, please feel free
to close this issue it at any moment in time!

**Comment by zerodytrash** [comment]
The script code is documented. Actually you should get all relevant infos by a simple research. Let me know if you have a specific question regarding the script.
