### ISSUE TITLE
error Report

### ISSUE THREAD

**Issue by big-cat-loaf** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#220]
### What happened?

Error  Report

### Platform

Userscript

### Version

2.5.9

### What browser are you on?

Chrome

### Browser version

Version 117.0.5938.132 (Official Build, ungoogled-chromium) (64-Bit)

### Link to the video

any, even on homepage

### Screenshots or Videos

[www.youtube.com-1697036375732.log](https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/files/12871488/www.youtube.com-1697036375732.log)

### About you

- [ ] I am a developer and/or have knowledge in programming

**Comment by drunkwinter** [comment]
Hi, these errors should not be causing any issues, but are important to fix nevertheless.

The fix will be included in the next release, until then i'm keeping this issue open.

Thanks for reporting.

**Comment by drunkwinter** [comment]
Fixed in [2.5.10](https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/releases/tag/v2.5.10)
