### ISSUE TITLE
"An error has occurred" Screen

### ISSUE THREAD

**Issue by peppermint-show** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#224]
### What happened?

What the title says basically, when using this script to watch age restricted content, for some reason an error screen will appear in front of the video itself, refreshing the page automatically.

However, you can still listen to the audio of the videos themselves and even use Youtube's keyboard shortcuts (F for fullscreen, K for pause/play, etc.).

I am running this script with the Firefox Extension "Violentmonkey", alongside another script to remove the comment section.

### Platform

Other (mention above)

### Version

2.5.2 (The actual script), 2.16.0 (The extension)

### What browser are you on?

Firefox

### Browser version

119.0.1 64 bit

### Link to the video

https://www.youtube.com/watch?v=7L4HUEkrWnk&list=WL&index=2

### Screenshots or Videos

![imagen](https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/assets/150557440/046dee1c-616b-47b3-b9ee-b38324964bda)

The text it's in Spanish but it basically says, "An error has occurred. Please try again later.". and it has an error code underneath said text (282054944).

### About you

- [X] I am a developer and/or have knowledge in programming

**Comment by D3SOX** [comment]
I'm using the same configuration (Firefox+Violentmonkey) and this also happens to me, but only in a private window.
As a workaround, you can fix it using keyboard shortcuts: Press `K` if the video doesn't play and `F` to fullscreen. Then you can even exit fullscreen and it works just fine.

**Comment by drunkwinter** [comment]
Hi, this issue was fixed a while ago in v2.5.7 and later.

**Comment by D3SOX** [comment]
Oh, I was mistaken about my installation method. I was actually using the Firefox extension but I just saw that it has been removed and therefore I'm stuck on 2.5.4. Kinda annoying that there's no way to know when an extension has been removed from the store.
Now, using the current version of the script with Violentmonkey works just fine!
