### ISSUE TITLE
Age restricted video does not play.

### ISSUE THREAD

**Issue by Apep-the-snek** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#226]
### What happened?

Age restricted video does not play. 

### Platform

Extension

### Version

2.16.0

### What browser are you on?

Firefox

### Browser version

120.0b4 (64-bit)

### Link to the video

https://www.youtube.com/watch?v=gh89BI-YMko

### Screenshots or Videos

![image](https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/assets/33030702/97bca745-570f-4e1f-b870-69fb3c057cb3)

### About you

- [ ] I am a developer and/or have knowledge in programming

**Comment by Apep-the-snek** [comment]
I found out that no videos worked after this, and i found out that i needed a couple other scripts blocking the youtube anti-adblocker thing, which i had naively just removed with CSS.
https://greasyfork.org/en/scripts/477498-youtube-adblock-ban-bypass
https://greasyfork.org/en/scripts/477390-remove-youtube-adblock-warnings
these two fixed it if you were wondering.

**Comment by Vmthyagaraj** [comment]
02/04/1972
