### ISSUE TITLE
Descriptions are gone again

### ISSUE THREAD

**Issue by interrupt-routine** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#228]
### What happened?

It seems like the script fails to retrieve the descriptions of age-restricted videos again. Like [last time](https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/issues/159), I can still find the description in the source:

```html
<body dir="ltr" no-y-overflow>
  <script nonce="...">
    var ytInitialPlayerResponse = {
       ..., "shortDescription" : "video description is there"
}
```

Logs:
```
Simple-YouTube-Age-Restriction-Bypass: playerResponse property set, contains sidebar: true
Simple-YouTube-Age-Restriction-Bypass: Trying Player Unlock Method #2 (TV Embedded Player)
Simple-YouTube-Age-Restriction-Bypass: playerResponse property set, contains sidebar: false
Simple-YouTube-Age-Restriction-Bypass: playerResponse property set, contains sidebar: false
```

Before these logs there is also a bunch of errors (`Failed to intercept Request() TypeError: url is null)` like [mentioned in this issue](https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/issues/220) that are apparently not relevant and have already [been fixed here](https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/pull/221/commits/976f68a3838ba43a38f342a581709bd394d0fc3e), release pending.

### Platform

Userscript

### Version

2.5.9

### What browser are you on?

Firefox

### Browser version

120.0.1

### Link to the video

https://www.youtube.com/watch?v=cT1QGn9Ntl0

### About you

- [X] I am a developer and/or have knowledge in programming

**Comment by drunkwinter** [comment]
Tried everything, but cannot seem to repro. Do you have the full version of the logs or is this everything?

**Comment by interrupt-routine** [comment]
These are all the logs emitted by the userscript, yes. Do you also want the userscript errors and/or logs from the entire page ?
____
I tried disabling every other extension I have save for Tampermonkey, but the problem still persists.

**Comment by drunkwinter** [comment]
I first want to rule out an issue with the userscript manager. Can you try it with [Violentmonkey](https://addons.mozilla.org/en-US/firefox/addon/violentmonkey/)? (don't forget to disable Tampermonkey first) 

If it works, then try disabling and reenabling Tampermonkey (there was a bug related to this sometime ago). If it still doesn't work then a full page log might be helpful. You could also try testing this on edge/chrome.

**Comment by interrupt-routine** [comment]
I can see descriptions again... no idea what changed. Sorry for the trouble and thanks for your help

**Comment by interrupt-routine** [comment]
And now gone again...
Running the script with Violentmonkey on Firefox  correctly unlocks the videos and their descriptions. Same when running it with Tampermonkey on Edge.

____
In the meantime, I just cobbled this quick-fix together to restore the description (it lacks the youtube pretty formatting  that would require creating some YouTube custom HTML elements):
```javascript
document.getElementById('snippet').innerHTML = ytInitialPlayerResponse.videoDetails.shortDescription;
```
It seems that  `shortDescription` (which confusingly seems to be the entire description) is always sent even if the video is age-restricted and the description is not displayed.

**Comment by drunkwinter** [comment]
I have no idea what the cause might be. Almost seems like a race condition.

About the description, I thought the description worked correctly? The `shortDescription` was actually a short description in the past, but it indeed seems to include everything now with the videos I've tested.

**Comment by interrupt-routine** [comment]
Sorry if I was not clear - I meant that the problem (no video description) reappeared with the combination Firefox + TamperMonkey; but is apparently neither due to Firefox nor TamperMonkey by themselves, since Firefox + ViolentMonkey works and Edge + TamperMonkey also works.

Hence why I have to fetch the `shortDescription` as a quick-fix (I want to keep using TamperMonkey and Firefox).
