### ISSUE TITLE
"Something went wrong, try again later"

### ISSUE THREAD

**Issue by Barricade386** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#229]
### What happened?

Every time I want to watch an age-restricted video, I get this message and the numbers 282054944

### Platform

Extension

### Version

2.5.4

### What browser are you on?

Firefox

### Browser version

120.0.1

### About you

- [ ] I am a developer and/or have knowledge in programming

**Comment by drunkwinter** [comment]
Hi, this issue was fixed a while ago in v2.5.7 and later.

**Comment by drunkwinter** [comment]
Also, unfortunately the extension got removed from Firefox Add-ons, so only installing the userscript version is possible.
