### ISSUE TITLE
Seems like Brave Adblock prevents to play videos.

### ISSUE THREAD

**Issue by CrashedLife** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#23]
Thread:
https://twitter.com/sqliCrashedLife/status/1413235281373933569

**Comment by dhntr** [comment]
sir this is not how issues are supposed to be used i think

**Comment by dhntr** [comment]
ok nevermind

**Comment by zerodytrash** [comment]
Moin,

I was able to reproduce the error. Brave Browser Shield tries to call the setter of the hijacked `ytInitialPlayerResponse` variable recursively. This ends in a `RangeError: Maximum call stack size exceeded`.

I added a check that should prevent the recursive function call.

https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/commit/d1b70a7b0b22344db6823396c85d68508f74c1d0

Let me know if it works.
