### ISSUE TITLE
does not stop the "Ad blockers not allowed onm youtube" pop up

### ISSUE THREAD

**Issue by CitizenDroid** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#231]
### What happened?

doesnt seem to work but when i check the script it states close popup is disabled and if i try and edit it it states it wont update any more if i do that!!!

### Platform

Userscript

### Version

2.8

### What browser are you on?

Chrome

### Browser version

Version 120.0.6099.111

### About you

- [ ] I am a developer and/or have knowledge in programming

**Comment by jan-ale** [comment]
do you have an ad blocker enabled? if yes then that would not be very surprising, this is not meant to stop that

**Comment by CitizenDroid** [comment]
> do you have an ad blocker enabled? if yes then that would not be very surprising, this is not meant to stop that

i tried it with and without adbock plus although it seems to have calmed down now but thanks for replying i reinstalled a few times so may have sorted it that way. thanks

**Comment by jan-ale** [comment]
you should probably close the issue then
