### ISSUE TITLE
Script not working - Youtube error 282054944, and audio continues playing in the background

### ISSUE THREAD

**Issue by Miehtz** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#233]
### What happened?

When watching age restricted videos I get the "Age-restricted video unlocked!" popup, then get maybe a second of video before the screen goes black and the error code 282054944 appears (attached screenshot), but the audio for the video keeps playing. Also included the error that showed in the inspect menu.

### Platform

Userscript

### Version

2.5.2

### What browser are you on?

Firefox

### Browser version

122.0

### Screenshots or Videos

![Screenshot 2024-02-04 191306](https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/assets/63133149/5b842686-d8e7-4189-ab9e-8d0bb8f12261)

![Screenshot 2024-02-04 191059](https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/assets/63133149/e969e051-e528-46a0-9f7c-7e2d63d0669c)

### About you

- [ ] I am a developer and/or have knowledge in programming

**Comment by drunkwinter** [comment]
Hi, this issue was fixed a while ago in v2.5.7 and later.

Unfortunately the extension got removed from Firefox Add-ons, so only installing the userscript version is possible.
