### ISSUE TITLE
Age Bypass Failing on https://www.youtube.com/watch?v=KBmEX9ZqBIU

### ISSUE THREAD

**Issue by zmcfate** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#235]
### What happened?

Attempting to access https://www.youtube.com/watch?v=KBmEX9ZqBIU gets me a demand to sign in.

### Platform

Extension

### Version

5.0.1

### What browser are you on?

Brave

### Browser version

1.62.162

### Link to the video

https://www.youtube.com/watch?v=KBmEX9ZqBIU

### About you

- [X] I am a developer and/or have knowledge in programming

**Comment by drunkwinter** [comment]
The video doesn't unlock because it's also paid content.
