### ISSUE TITLE
Still get age restriction on this Yt video. Works on other video's.

### ISSUE THREAD

**Issue by pendoza** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#24]
https://www.youtube.com/watch?v=IYndqz5i7mk

**Comment by Blumlaut** [comment]
Can Reproduce on Firefox Nightly 91.0a1 (2021-07-11) (64-bit), Script version 0.9.4,

**Comment by pentiumvsamd** [comment]
same on this https://www.youtube.com/watch?v=Pn7oEYe4ePc

**Comment by 89z** [comment]
Same for this  https://www.youtube.com/watch?v=Cr381pDsSsA

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/29086

**Comment by 89z** [comment]
That video requires authentication, with either OAuth `Authorization` header or `Cookie` headers.

**Comment by zerodytrash** [comment]
@pendoza @pentiumvsamd both videos are playable in the latest script version. So it should be fixed now. Let me know if there are still issues.
