### ISSUE TITLE
Does it work anymore? (on chrome)

### ISSUE THREAD

**Issue by j7979141** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#240]
### What happened?

The script doesn't work for me.

### Platform

Extension

### Version

2.5.9

### What browser are you on?

Chrome

### Browser version

125.0.6422.142

### Link to the video

https://www.youtube.com/watch?v=ks1CBTwtaU8

### About you

- [ ] I am a developer and/or have knowledge in programming

**Comment by real-F-00** [comment]
doesn't seem like it works anymore.

**Comment by tiyn** [comment]
Doesn't work on Firefox either

**Comment by drunkwinter** [comment]
A couple of questions:
- Does this occur on YouTube or a site that embeds the YouTube video?
- Do you have any other add-ons installed, and if so, could you please verify that you get the same behavior with everything else disabled?
- Could you provide us the logs in the developer console in a screenshot or text format? Press F12 and filter for "Simple-YouTube-Age-Restriction-Bypass" after you notice the behavior.
