### ISSUE TITLE
Doesn't work anymore for me

### ISSUE THREAD

**Issue by Rik034** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#25]
I'm on OperaGX but I tried on Firefox and Chrome with no extensions installed other than tampermonkey and it doesn't skip age restriction anymore and refreshing the page doesn't help. I don't know if it's a bug or YouTube changed something but it stopped working for me.

**Comment by 89z** [comment]
example video?

**Comment by zerodytrash** [comment]
everything should work again at the moment. if you still have problems, let me know.
