### ISSUE TITLE
Age restricted video tab crashes on Brave

### ISSUE THREAD

**Issue by andris86** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#250]
### What happened?

When I open age restricted video on Youtube, tab crashes. I am using Brave.

### Platform

Userscript

### Version

2.5.10

### What browser are you on?

Brave

### Browser version

1.68.141

### About you

- [ ] I am a developer and/or have knowledge in programming

**Comment by drunkwinter** [comment]
Duplicate of #236.

Please see the issue above.

**Comment by ninjagaiden2345** [comment]
Yea this script works fine in Edge but stops Brave from loading YouTube at all or doesn't bypass the age verification
