### ISSUE TITLE
Script not working 17/10/2024

### ISSUE THREAD

**Issue by sliperhr** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#262]
### What happened?

the script is not working and keep showing the error Unable to unlock this video 🙁 - More information in the developer console (ProxyError)

### Platform

Extension

### Version

2.5.10

### What browser are you on?

Chrome

### Browser version

129.0.6668.101

### Link to the video

https://www.youtube.com/watch?v=W26PZOktM3s

### About you

- [ ] I am a developer and/or have knowledge in programming

**Comment by joaquinito2070** [comment]
I'll fix it this afternoon, but I don't know if I'll be able to get it.

**Comment by joaquinito2070** [comment]
That's right, it seems that our basic plan cloud instance has expired, so it will take days to get it back, as we have to find a cloud provider, register, and also implement the proxy server on Kubernetes and also autoscaler, so that it doesn't go down anymore. More news if something happens.

**Comment by itzzzryze** [comment]
i just wanted to thank the dev "team" (idk if its a team or a single guy) for being so active on such a usefull yet underrated project !

**Comment by valtoree** [comment]
Thank u dev/s for all ur awesome work. This has just started being a nuisance for me. So looking forward for a fix whenever that may be. ❤️

**Comment by drunkwinter** [comment]
Hey guys, first of all thanks for the support. Unfortunately the issue is a bit complicated and the sustainability of the project is now kind of uncertain.

You can read more about the issue here: https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/issues/263#issuecomment-2450802182

**Comment by drunkwinter** [comment]
Closing this in favor of other already opened issues.

Duplicate of https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/issues/263.
