### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by MusicaFM** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#266]
### What happened?

El proxy está off y por eso actualmente no funciona, probado en kiwibrowser y firefox android

### Platform

Other (mention above)

### Version

Actual

### What browser are you on?

Chrome

### Browser version

Actual

### About you

- [ ] I am a developer and/or have knowledge in programming

**Comment by drunkwinter** [comment]
Duplicate of #262, #263.
