### ISSUE TITLE
Can't work 11/3

### ISSUE THREAD

**Issue by Owen-956** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#267]
### What happened?

can't work

### Platform

Userscript

### Version

	2.5.11

### What browser are you on?

Chrome

### Browser version

130.0.6723.92 

### About you

- [ ] I am a developer and/or have knowledge in programming

**Comment by drunkwinter** [comment]
Duplicate of https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/issues/263.
