### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by krolmiki2011** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#269]
### What happened?

When i tried open video is not working (proxy error) PLEASE FIX THIS!

### Platform

Extension

### Version

2.5.10

### What browser are you on?

Firefox

### Browser version

130.0

### About you

- [ ] I am a developer and/or have knowledge in programming

**Comment by drunkwinter** [comment]
Duplicate of https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/issues/263.
