### ISSUE TITLE
It stopped working

### ISSUE THREAD

**Issue by hyoukafuwa** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#27]
It doesn't do its job anymore.

**Comment by CapoFantasma97** [comment]
I concur. Today, it stopped working.

**Comment by Incineratinq** [comment]
same here

**Comment by enzomtpYT** [comment]
i think youtube fixed it sad for all of us

**Comment by ChandlerBing1994** [comment]
Same. It stopped working a few hours ago.

**Comment by RomanPlayer22** [comment]
Same, i tried to watch HowToBasic - How to Make a Rainbow Cake and Ballistic from Friday Night Funkin (Bass boosted) and it said verify

**Comment by Arczi008TV** [comment]
Needs update

**Comment by zizipoil** [comment]
same

**Comment by hyoukafuwa** [comment]
![image](https://user-images.githubusercontent.com/47471351/126719881-3428de99-6ed2-41a7-bc9d-8e04038d851b.png)

**Comment by MinePlayersPE** [comment]
Looks like they finally closed the get_video_info endpoint, changing clients also doesn't work

**Comment by zerodytrash** [comment]
There seems to be no way to access the videos without login anymore. So now I have implemented a public account proxy to retrieve the video info. A shared google account is integrated on the server side. I don't know if google has a rate limit for the ``/youtubei/v1/player`` requests. Therefore this is only an experiment for now. It can break again at any time. But feel free to test the new version.

**Comment by zizipoil** [comment]
so far so good.
Just wanted to thank you for trying to be our David against greedy Goliath Google.

**Comment by FakeDomi** [comment]
> 
> 
> There seems to be no way to access the videos without login anymore. So now I have implemented a public account proxy to retrieve the video info. A shared google account is integrated on the server side. I don't know if google has a rate limit for the `/youtubei/v1/player` requests. Therefore this is only an experiment for now. It can break again at any time. But feel free to test the new version.

It's sad that it had to come to this. Thank you for keeping up with their bullshit, you are an absolute legend.
Does the account used for the proxy need age verification? Asking just in case they decide to ban yours for spamming the api.

**Comment by MinePlayersPE** [comment]
>Does the account used for the proxy need age verification?

IIRC yes, since the EU age verification is also server-side. Looks like there might be a workaround involving old YouTube versions that still work, but I still haven't figured it out

**Comment by MinePlayersPE** [comment]
Should be solved by https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/commit/fd96e62ddf57110620628a71b5d15a54d3b75c9b

**Comment by zerodytrash** [comment]
We now have two new bypass methods.
1.  ``/youtubei/v1/player`` with ``clientScreen``:``EMBED`` (has similar success rate as the last ``/get_video_info`` bypass) 
(see https://github.com/yt-dlp/yt-dlp/issues/574#issuecomment-887171136)
2. The youtube account proxy (https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/issues/27#issuecomment-887083447)

The first method is tried first and the second is used as a fallback. Perhaps these bypass methods remain longer than two weeks :)

@FakeDomi if you use a IP located in US, it should work without age confirmation. In the account proxy configuration a corresponding http proxy can be set, if you don't have a US server/ip.
