### ISSUE TITLE
Request: Post the script to Greasyfork, etc.

### ISSUE THREAD

**Issue by Dyras** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#3]
Hello! Just a small request. Could you post the script to Greasyfork and other similar sites? It means more people would find this great script. Thanks :)

**Comment by zerodytrash** [comment]
Sure, here we go: https://greasyfork.org/en/scripts/423851-simple-youtube-age-restriction-bypass :)
I have never published a script on Greasyfork before. Hope this is fine.

**Comment by Dyras** [comment]
@zerodytrash you may want to consider posting your script here too
https://openuserjs.org/

**Comment by zerodytrash** [comment]
@Dyras done, https://openuserjs.org/scripts/zerodytrash/Simple_YouTube_Age_Restriction_Bypass
