### ISSUE TITLE
Stopped working, please fix!

### ISSUE THREAD

**Issue by Jonybtw** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#30]
Stopped working.

**Comment by Blumlaut** [comment]
![image](https://user-images.githubusercontent.com/13604413/126845818-b7744eab-118e-48a0-a7da-f5f89fbba1e6.png)
ya think?

**Comment by Jonybtw** [comment]
> ![image](https://user-images.githubusercontent.com/13604413/126845818-b7744eab-118e-48a0-a7da-f5f89fbba1e6.png)
> ya think?
