### ISSUE TITLE
Alternative: ProxTube (and other YouTube auto-proxy browser extensions)

### ISSUE THREAD

**Issue by CapoFantasma97** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#32]
ProxTube works wonderfully nicely, and does even more, by bypassing regional block and other types of restrictions.

https://addons.mozilla.org/firefox/addon/proxtube/

When you load a page that's restricted in some form (e.g. age restricted) it automatically detects that, and loads a proxied version seamlessly, inside YouTube itself. No third party pages or other inconveniences. The end result is very similar to this script (when it used to work).

If you do not use Firefox, I'm confident there are similar extensions for your browser of choice (although, if you don't trust giving YouTube your ID, while using Chrome... kinda counterintuitive, is it not?).

**Comment by SunburntRock89** [comment]
Cannot advocate: Just refreshed and refreshed and refreshed the video, not bypassing the restriction.

**Comment by CapoFantasma97** [comment]
> 
> 
> Cannot advocate: Just refreshed and refreshed and refreshed the video, not bypassing the restriction.

Which video are you trying to bypass?

**Comment by SunburntRock89** [comment]
> Which video are you trying to bypass?
@CapoFantasma97 https://www.youtube.com/watch?v=7t0SqerlBA0

**Comment by CapoFantasma97** [comment]
> 
> 
> > Which video are you trying to bypass?
> 
> @CapoFantasma97 https://www.youtube.com/watch?v=7t0SqerlBA0

Works for me. I'm at a loss. I have no idea what to tell you. Maybe someone more knowledgeable might chime in and solve this.

![test](https://user-images.githubusercontent.com/9368910/127030806-bde04aa9-5015-472b-a45a-71dc6fd83849.png)

**Comment by zerodytrash** [comment]
The general problem with this proxy extensions is that a Google account is required. Not everyone wants a Google account. But yes, if you have an account you can bypass the verification from the USA.

**Comment by CapoFantasma97** [comment]
I am European (Italy) so I can confirm it works there too. If someone will have issues with the script not working in the future, this might be a good alternative.

**Comment by zerodytrash** [comment]
Will keep the issue open for people who are looking for alternatives.

**Comment by MinePlayersPE** [comment]
Note: As of now, we're getting sporadic age verification requests for EU accounts proxying outside of the EU (e.g. current account proxy used by this extension)

**Comment by zerodytrash** [comment]
> Note: As of now, people are getting sporadic age verification requests for EU accounts proxying outside of the EU (e.g. current account proxy used by this extension) which could indicate a sweeping change

Yes, changing the IP address is no longer sufficient. The regulations from the country which is assigned in the Google Account apply. I don't know if its possible change the location afterwards. Creating a new Google account via a US VPN can solve the problem. But browser extensions like Proxtube no longer work for this purpose.
