### ISSUE TITLE
[Enhancement] Implement newly-found youtubei/player based age-gate bypass

### ISSUE THREAD

**Issue by MinePlayersPE** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#34]
https://github.com/yt-dlp/yt-dlp/issues/574#issuecomment-887171136
Seems like it has the same success rate as get_video_info. While you could just slap it onto the current proxy system, it's probably better to implement it on the userscript itself.

**Comment by zerodytrash** [comment]
This is incredible! This bypass is tried first and then as a fallback the account proxy.

https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/commit/fd96e62ddf57110620628a71b5d15a54d3b75c9b
