### ISSUE TITLE
Not working on age restricted music video

### ISSUE THREAD

**Issue by Kosert** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#36]
Specifically this one:
https://www.youtube.com/watch?v=UUw15324M1A

I can see there are some 403s in console:
![image](https://user-images.githubusercontent.com/22669255/127194491-ccce5cbc-f860-4519-9e12-d24a41ef92b5.png)

**Comment by zerodytrash** [comment]
Thanks for reporting. This should be fixed now!

https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/commit/50cec1d741159eab09021a77a74bcae2b2d21c75

**Comment by krystian3w** [comment]
Działa, słychać ponownie rzucanie mięskiem.

**Comment by zerodytrash** [comment]
:)
