### ISSUE TITLE
Support for  mobile version of youtube (m.youtube.com)

### ISSUE THREAD

**Issue by openwick** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#37]
Hi I am currently using this script on tampermonkey in firefox nightly of android and this script only works if i turn on the desktop mode inside the browser.

So please add support to the mobile version of youtube(https://m.youtube.com) as well.

**Comment by zerodytrash** [comment]
Hi, have tweaked the script. Now it works also for the mobile web page of youtube. Tested with Firefox Nightly & Tampermonkey for Android. Let me know if it works for you too.

https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/commit/d2fff405d835fe97705bafd22bc6d0ba2850d482

![image](https://user-images.githubusercontent.com/59258980/127395469-6b8ee8dc-b10c-4a19-96c3-7ac6d86ac37b.png)

**Comment by openwick** [comment]
Yes its working on mobile. Thanks for implementing it :)

**Comment by ArjixWasTaken** [comment]
> Hi I am currently using this script on tampermonkey in firefox nightly of android and this script only works if i turn on the desktop mode inside the browser.
> 
> So please add support to the mobile version of youtube(https://m.youtube.com) as well.

You should use the [vanced](https://vancedapp.com/) app, it not only removes ads, but it also bypass age restrictions and it also implements SponsorBlock

**Comment by MinePlayersPE** [comment]
>it also bypasses age restrictions

Note: It doesn't, atleast not intentionally
I'm pretty sure you're talking about the old versions that currently bypass age *verification*, which seems to be chalked up to A/B testing

**Comment by zerodytrash** [comment]
Currently the official youtube app no longer asks me to confirm my age. never submitted any credit card or id details. it is an EU account.

**Comment by ArjixWasTaken** [comment]
> Currently the official youtube app no longer asks me to confirm my age. never submitted any credit card or id details. it is an EU account.

I guess that's why I had no age verification shit on vanced.
I'm also in EU.
