### ISSUE TITLE
Invalid syntax for older browsers

### ISSUE THREAD

**Issue by v3core** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#46]
hi, the syntax "a?.b" is invalid on slightly older browsers (example: "playerResponse?.playabilityStatus?.status !== "OK"")
could you explain what does it do so one could replace it with a longer functional one to get the script to work?

**Comment by zerodytrash** [comment]
hi,
"Optional chaining" is an ECMAScript 2020 Feature.
See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining

Which browser (version) do you use?

**Comment by v3core** [comment]
chromium 70 release

**Comment by zerodytrash** [comment]
Chromium/Chrome 70 was released in 2018, see https://en.wikipedia.org/wiki/Google_Chrome_version_history
I would recommend you to use a current browser version.

**Comment by v3core** [comment]
thank you for the clearance regarding the scripting

**Comment by v3core** [comment]
window.ytcfg.data_.[key] ?? window.ytcfg.get.(key);
why the dot before the [ or ( ? tampermonkey considers it invalid syntax
