### ISSUE TITLE
Feature Request: Invidious

### ISSUE THREAD

**Issue by jw243** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#47]
Hi,
I've just discovered your script and it is amazing. Thanks for all your effort!
Do you think it would be possible to make the script work with videos on **invidious**, too? That would be awesome.
Thanks a lot.

**Comment by zerodytrash** [comment]
This script interacts with the YouTube frontend to unlock videos. Invidous has a completely different frontend. Everything would have to be recreated.

It would be easier if Invidous implemented the bypass used here directly in its backend. According to the codebase, this has already been done. See https://github.com/iv-org/invidious/blob/e9add69e267c143925ba51d54c03deaba2e0e85a/src/invidious/helpers/youtube_api.cr#L39

**Comment by jw243** [comment]
Thanks a lot for your quick reply!
