### ISSUE TITLE
Occasionally it doesn't work

### ISSUE THREAD

**Issue by CapoFantasma97** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#5]
Rarely, it happens that it won't skip age verification; reloading the page however solves it, so it's not a big deal. Not sure why.

I'd also like to thank you for your work. Handing out sensitive data to Google like a copy of ID/credit card for "age verification" is ridicolous and should be illegal.

**Comment by zerodytrash** [comment]
Thank you for the feedback.
If you let me know which browser you are using and which browser extensions you have enabled, I can try to reproduce the bug.

**Comment by CapoFantasma97** [comment]
> 
> 
> Thank you for the feedback.
> If you let me know which browser you are using and which browser extensions you have enabled, I can try to reproduce the bug.

Firefox for Windows
Extensions: uBlock Origin, Nano Defender, Disconnect, Decentraleyes, SponsorBlock, Tampermonkey.

**Comment by zerodytrash** [comment]
hi,

https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/commit/1874086c0fed5d7c7bbfa1ccd6a56be3229bdae1

Does that fix your problem?
