### ISSUE TITLE
Currently not working

### ISSUE THREAD

**Issue by tueksta** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#51]
Tampermonkey and this script installed and in latest version, logged in with my google account, but when I go to https://www.youtube.com/watch?v=HcXNPI-IPPM I still see the age blocker.

**Comment by zerodytrash** [comment]
Hi, the unlock of the mentioned video works for me. If the unlocking fails, you can find more information in the developer console. Please share this information with us.
