### ISSUE TITLE
[Enhancement/Feature Request] Reinstate descriptions for age-restricted YouTube videos

### ISSUE THREAD

**Issue by LifeLineRH** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#52]
Self-explanatory. I know that [the video sidebar was able to be reinstated](https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/issues/16), but I'd also like for descriptions themselves to be reinstated too, since they seem to be forcibly removed as well.

**Comment by zerodytrash** [comment]
hi, 

https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/commit/09da4a68c3867ce8df53cb8747afeec930806f56

I was able to solve the problem for me. Does this also work for you?

**Comment by LifeLineRH** [comment]
Yes, it appears it does now. Thank you!
