### ISSUE TITLE
Breaks uBlock Origin?

### ISSUE THREAD

**Issue by D3SOX** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#6]
Not sure what causes this but I always get this before the video starts when the script is enabled, even when the video is not age restricted:
![image](https://user-images.githubusercontent.com/24937357/114996596-4506e300-9e9f-11eb-9377-0bf2aea7d0e2.png)

Using Firefox 87.0 with Tampermonkey 4.12.6132

**Comment by Dyras** [comment]
Noticed the same thing. It usually seems to pass after a few seconds though.

**Comment by D3SOX** [comment]
As a workaround I only enable the script when YouTube prompts me for an age confirmation.

**Comment by Dyras** [comment]
Hmmm for me, this seems to have been a collision with another script. After disabling that script, it now seems to work 100%.

**Comment by D3SOX** [comment]
Which script? I don't have any other Tampermonkey scripts installed and I just tried it in a private window.
I enabled all the extensions to run in a private window and it didn't happen. Seems weird because in a normal window I can reproduce this with the same video every time. Can I provide some kind of logs?

**Comment by Denton0451** [comment]
I'm having a similar issue. The script kills of uBlock Origin for me and it stops blocking video player ads when I enable the script in Tampermonkey.

**Comment by Dyras** [comment]
Last few days I've noticed I get ads even with uBlock enabled. Hmm.

**Comment by ner00** [comment]
I just get adds with this script enabled, and as someone mentioned previously, I only enable this script when needed due to that issue.

**Comment by zerodytrash** [comment]
hi,

https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/commit/1874086c0fed5d7c7bbfa1ccd6a56be3229bdae1

That fixed the problem in my case. Can you confirm this?

**Comment by JustOff** [comment]
I'm afraid https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/commit/1874086c0fed5d7c7bbfa1ccd6a56be3229bdae1 does not clear the issue, at least I still always see the pre-roll ad on [this](https://www.youtube.com/watch?v=5uTjLd6USJo) video.

**Comment by leewp14** [comment]
Not using uBlock, however the commit https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/commit/1874086c0fed5d7c7bbfa1ccd6a56be3229bdae1 does solves the issue on Ghostery.

**Comment by D3SOX** [comment]
It seems to have fixed the issue for me. Thank you! Should I close this issue?

@JustOff I don't get an ad on the video you linked

**Comment by JustOff** [comment]
For me uBlock Origin successfully removes the pre-roll ad in [this](https://www.youtube.com/watch?v=5uTjLd6USJo) video in Chrome 91.0.4472.77, even with the bypass script 0.9.1, but in Firefox 89 the ad is still shown both with 0.9.1 and 0.9.2.

**Comment by ner00** [comment]
I'm not having any issue with Firefox as I used to have before, but sometimes it's a bit random. I'll just leave the script enabled by default and see if I get any pre-roll.

**Comment by ACGaming** [comment]
No issues so far with the latest script and Firefox 89.

**Comment by devilAPI** [comment]
Works fine for me on Chrome
 `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36` with `Violentmonkey` and Script Version `0.9.3`
