### ISSUE TITLE
[request] use of proxy in external application

### ISSUE THREAD

**Issue by lekma** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#62]
Hi @zerodytrash,

I maintain an [invidious kodi plugin](https://github.com/lekma/plugin.video.invidious) and was wondering if I could use your proxy to help users bypass age gating of videos when playing them directly from yt.

That would mean increased traffic on your server (I don't think it would be that noticeable, there aren't that many users of the plugin), that's why I request your authorization before going forth with setting it up.

thanks for your help

**Comment by xlovinglyx** [comment]
lol lekma.....

**Comment by lekma** [comment]
> lol lekma.....

???

**Comment by xlovinglyx** [comment]
You really think connecting several computers to the authors ip will allow him to have a fluent connection ?
& that moreover, he'll open his connection to all sorts of computers, infected or not ? & even better, 
pay for free hosting if it's website based ? )) i can only expect an almost similar reply from zerodytrash ((

**Comment by zerodytrash** [comment]
hi, you can host your own account proxy with a little effort. 
Here is the source code: https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/tree/main/account-proxy

**Comment by lekma** [comment]
> hi, you can host your own account proxy with a little effort.
> Here is the source code: https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/tree/main/account-proxy

yeah I know, unfortunately I can't.

thanks for your help
