### ISSUE TITLE
Video description and the videos on right side not appearing

### ISSUE THREAD

**Issue by RomanPlayer22** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#76]
I tried watching HowToBasic - How To Make a Rainbow Cake
but the description didnt appear; neither did the sidebar of videos
![Snímek obrazovky 2021-09-10 104651](https://user-images.githubusercontent.com/47942792/132827057-89234316-2ed7-4c23-806b-7604b44698ab.jpg)

**Comment by DrunkWinter** [comment]
Already working on it.

**Comment by ztgasdf** [comment]
@RomanPlayer22 I've noticed that this only happens for me when I'm signed into an age restricted account. If I sign out, then the description and sidebar loads.

**Comment by ArjixWasTaken** [comment]
So a possible solution is to make those requests w/o authentication?

**Comment by DrunkWinter** [comment]
> So a possible solution is to make those requests w/o authentication?

Already fixed in the latest release.

**Comment by ArjixWasTaken** [comment]
> Already fixed in the latest release.

You are a god 😄

**Comment by DrunkWinter** [comment]
I think a part of why this is not closed is because only the GitHub release got updated. 
The GreasyFork & OpenUserJS versions need to be uploaded. @zerodytrash

**Comment by zerodytrash** [comment]
> The GreasyFork & OpenUserJS versions still need to be uploaded. @zerodytrash

Done. Thanks @DrunkWinter
