### ISSUE TITLE
The Bypass used to work, today it isnt working?

### ISSUE THREAD

**Issue by MrJeffOfficial** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#9]
yesterday it worked fine, but today it doesn't work. even refreshing the page doesn't work. now it just displays the "verify your age" page. let me know if you need more info

btw im using the brave browser but i also tested it on chrome and it also doesn't work

**Comment by Dyras** [comment]
I'm using Firefox and I've had a different strange problem starting today. It skips the "verify your age" but I get the ads. Hmm.

**Comment by zerodytrash** [comment]
hi @MrJeffOfficial,

do you have a video link where the problem occurs? At the moment I can't reproduce it.

**Comment by MrJeffOfficial** [comment]
> hi @MrJeffOfficial,
> 
> do you have a video link where the problem occurs? At the moment I can't reproduce it.

for example, this song : https://www.youtube.com/watch?v=duZsTr6_-mg but i also think it happens for other videos as well

**Comment by zerodytrash** [comment]
I have just tried to reproduce the problem again. Unfortunately without "success".

Without Simple-YouTube-Age-Restriction-Bypass:

![2021-05-16 23_48_08-SHAKIRA! FT  EGOVERT (Prod  nategoyard) - YouTube](https://user-images.githubusercontent.com/59258980/118413812-7a227300-b6a1-11eb-9125-730c25214607.png)

With Simple-YouTube-Age-Restriction-Bypass:

![2021-05-16 23_48_29-SHAKIRA! FT  EGOVERT (Prod  nategoyard) - YouTube](https://user-images.githubusercontent.com/59258980/118413813-7abb0980-b6a1-11eb-8c54-91d3392cf8d1.png)

The video works fine. I was also not logged in. Are you logged in to your Google Account @MrJeffOfficial ? If so, try logging out. 

Check the developer console (F12) to see if there are any error messages from the script like:

![2021-05-16 23_58_26-Einstellungen](https://user-images.githubusercontent.com/59258980/118414033-aa1e4600-b6a2-11eb-976d-8794a6d9786b.png)

If so, please let me know.

**Comment by fifa000001** [comment]
Hi,
same thing on Firefox, I am sending what I found in dev. console.
![Snímek obrazovky (157)](https://user-images.githubusercontent.com/55358457/118470779-4c701500-b707-11eb-8f1b-c051fea6c672.png)

**Comment by MrJeffOfficial** [comment]
> I have just tried to reproduce the problem again. Unfortunately without "success".
> 
> Without Simple-YouTube-Age-Restriction-Bypass:
> 
> ![2021-05-16 23_48_08-SHAKIRA! FT EGOVERT (Prod nategoyard) - YouTube](https://user-images.githubusercontent.com/59258980/118413812-7a227300-b6a1-11eb-9125-730c25214607.png)
> 
> With Simple-YouTube-Age-Restriction-Bypass:
> 
> ![2021-05-16 23_48_29-SHAKIRA! FT EGOVERT (Prod nategoyard) - YouTube](https://user-images.githubusercontent.com/59258980/118413813-7abb0980-b6a1-11eb-8c54-91d3392cf8d1.png)
> 
> The video works fine. I was also not logged in. Are you logged in to your Google Account @MrJeffOfficial ? If so, try logging out.
> 
> Check the developer console (F12) to see if there are any error messages from the script like:
> 
> ![2021-05-16 23_58_26-Einstellungen](https://user-images.githubusercontent.com/59258980/118414033-aa1e4600-b6a2-11eb-976d-8794a6d9786b.png)
> 
> If so, please let me know.

Hello, even when logging out it won't work. but i screenshotted the error messages, here are them 
![Screenshot (427)](https://user-images.githubusercontent.com/38805169/118616567-1b084f80-b7c2-11eb-8df9-44afedf42f03.png)
![Screenshot (428)](https://user-images.githubusercontent.com/38805169/118616569-1ba0e600-b7c2-11eb-9594-605b92b5f8dd.png)
![Screenshot (429)](https://user-images.githubusercontent.com/38805169/118616571-1c397c80-b7c2-11eb-94c8-6d8c61366a0a.png)

**Comment by 930r** [comment]
I had the same issue but logging out fixed it.

**Comment by KokoSoft** [comment]
I have the same problem. In my case, youtube return 404 error for https://www.youtube.com/get_video_info?video_id=. All video metadata is included in [html code](https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/files/6504812/https._www.youtube.com_watch.v.e_S9VvJM1PI.txt) . Go to https://www.youtube.com/watch?v=e_S9VvJM1PI and search for <script type="application/ld+json".

**Comment by CodinTime** [comment]
change line 113:
xmlhttp.open("GET", "/get_video_info?video_id=" + encodeURIComponent(videoId), false); // Synchronous!!!
to:
xmlhttp.open("GET", "/get_video_info?html5=1&video_id=" + encodeURIComponent(videoId), false); // Synchronous!!!

enjoy :)

**Comment by CodinTime** [comment]
@KokoSoft @Dyras @MrJeffOfficial @zerodytrash 

Adding "html5=1" in line 113 and 120 solve the problem

"/get_video_info?html5=1&video_id="

**Comment by InsaanNotFound** [comment]
I can confirm this, modified my script with @CodinTime instructions and it works flawlessly now. Side note; loading restricted video takes longer now (unknown cause)

**Comment by KokoSoft** [comment]
@CodinTime : I confirm, the patch fixes the problem. Returning a 404 error is very confusing.

**Comment by ner00** [comment]
@CodinTime Thanks! Worked for me too.

**Comment by Braintoe** [comment]
@CodinTime : Thanks! I can confirm as well that this fix works.

**Comment by zerodytrash** [comment]
Fix added 

https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/commit/3301ed42d9beb343e997e4b058ded2bbd2d17b38

Thanks @CodinTime !
