### ISSUE TITLE
get unlocked player call fails with a 410 status

### ISSUE THREAD

**Issue by sproclavism** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#95]
Hey, is this something that you have encountered before? I've tried disabling my adblocker, but couldn't get the extension to work.
![image](https://user-images.githubusercontent.com/8351931/141647695-a5a1d3ab-5a52-44df-bf7f-b871369cad75.png)
Browser I'm using is brave.

copyable video id CXuxQQI_9SU

did a (really short) debug and found that the playability status was LOGIN_REQUIRED, so should be unlockable if I understood the code correctly

**Comment by zerodytrash** [comment]
Hi,

It looks like you are using an old version of the script. The `/get_video_info` endpoint no longer exists. 
Please update to the latest version.

**Comment by sproclavism** [comment]
That's strange, because I had just updated the script to its latest version before trying. I've just restarted my browser, and now indeed it is working.
Thanks for the help!

also, damn I got rickrolled haha
